# Java
  - name: Install Java 1.7
    yum: name=java-1.7.0-openjdk state=present

# MariaDB
# Mysql dependency that needs to be removed in order to install MariaDB
  - name: Remove mysql-libs package
    yum: name=mysql-libs state=removed

  - name: Install MariaDB 
    yum: name={{ item }} state=present
    with_items:
      - MariaDB-server.x86_64
      - MariaDB-client.x86_64
 
  - name: Start MariaDB Service
    service: name=mysql state=started enabled=yes

# RabbitMQ
  - name: Install RabbitMQ Server
    yum: name=rabbitmq-server state=present

  - name: Start RabbitMQ Service
    service: name=rabbitmq-server state=started enabled=yes

# Redis
  - name: Install Redis Server
    yum: name=redis state=present

  - name: Create Redis user
    user: name=redis createhome=no

  - name: Create Redis data folder
    file: path=/var/lib/redis/ owner=redis group=redis state=directory

  - name: Create Redis log folder
    file: path=/var/log/redis owner=redis group=redis state=directory

  - name: Start Redis Server
    service: name=redis state=started enabled=yes

# Apache
  - name: Install Apache2 httpd Server
    yum: name=httpd state=present

  - name: Set Apache2 httpd Service enabled at start up
    service: name=httpd enabled=yes

