---
- name: Download EPEL Repo
  get_url: url=http://mirror-fpt-telecom.fpt.net/fedora/epel/6/i386/epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm

- name: Install EPEL Repo
  yum: name=/tmp/epel-release-6-8.noarch.rpm state=present

- name: Install libselinux-python
  yum: name=libselinux-python state=present
